name: MarshmallowMongoengineCI
on:
  pull_request:
  push:
    branches:
      - master
  create:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: psf/black@stable

  build-n-publish:
    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Build wheel for PyPI and TestPyPI
        run: |
          pip install wheel
          python setup.py sdist bdist_wheel
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
