name: MarshmallowMongoengineCI
on:
  pull_request:
  push:
    branches:
      - master
  create:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
